load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mathlib",
    srcs = ["src/mathlib.go"],
    importpath = "example.com/apps/go/src/mathlib",
    visibility = ["//visibility:public"],
)
