# load("@rules_cc//cc:cc_test.bzl", "cc_test")

# cc_test(
#     name = "mathlib_test",
#     srcs = ["test_mathlib.c"],
#     deps = [
#         "//apps/cc:mathlib_cc",
#         "@criterion",  # externe Criterion-Instanz
#     ],
# )

# cc_test(
#     name = "mathlib_buggy_test",
#     srcs = ["test_mathlib_buggy.c"],
#     # tags = ["manual"],  # absichtlich fehlschlagend
#     deps = [
#         "//apps/cc:mathlib_buggy_cc",
#         "@criterion",
#     ],
# )
